# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicketAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picket',
            name='person_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picket',
            name='place_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
