# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PicketAdminApp', '0002_auto_20171127_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('poll_picket', 'poll picket'), ('accept_picket', 'accept picket'), ('info_picket', 'info picket'), ('geo_picket', 'geo picket')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picket',
            name='plases',
            field=models.ManyToManyField(blank=True, null=True, to='PicketAdminApp.Place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='PicketAdminApp.Person'),
        ),
    ]
