# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicketAdminApp', '0004_auto_20171130_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picket',
            name='plases',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='PicketAdminApp.Place'),
        ),
    ]
