# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PicketAdminApp', '0005_auto_20171130_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PicketAdminApp.Person'),
        ),
    ]
