# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicketAdminApp', '0006_auto_20171130_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='telegram_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
