# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicketAdminApp', '0007_auto_20171130_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picket',
            name='plases',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
