# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicketAdminApp', '0008_auto_20171203_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
